[package]
name = "Examples"
version = "0.0.0"

[addresses]
hello_blockchain = "0xa446c4bb2b53467a8e94062f69cca19c78da481783273119887c0e30b6c8872a"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "devnet" }
