image: gitpod/workspace-full

tasks:
  - init: >
      sudo apt-get update &&
      sudo apt-get install -y curl git-all cmake gcc libssl-dev pkg-config libclang-dev libpq-dev build-essential &&
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y &&
      source $HOME/.cargo/env &&
      rustup update stable
