[package]
name = "stackcoin"
version = "1.0.0"
authors = []

[addresses]
StackCoin = "_"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"