apiVersion: v1
kind: ServiceAccount
metadata:
  name: linera-admin
---
# To ease development, we define a single admin service account
# which is admin over the entire cluster.
# Over time this will be replaced with a collection of service accounts
# with more granular permissions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: linera-admin
subjects:
  - kind: ServiceAccount
    name: linera-admin
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io